import './css/variables.css'
import './css/keyframes.css'
import './css/blockPositions.css'
import './css/blockCommon.css'

import './css/bridgeBottomLeft.css'
import './css/bridgeBottomRight.css'
import './css/bridgeLeft.css'
import './css/bridgeRight.css'
import './css/bridgeTopLeft.css'
import './css/bridgeTopLeftCorner.css'
import './css/bridgeTopRight.css'
